from flask import Flask, request, render_template, redirect, url_for, session, jsonify
import os
import time
import datetime
import pandas as pd

# Import modules
from models.recommendation import RecommendationSystem
import history_manager

from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)
app.secret_key = os.environ.get('SECRET_KEY', 'supersecretdevkey')

DATA_DIRECTORY = 'data'

# --- Initialize Database and Recommendation System ---
history_manager.init_db() # This also creates data dir

print(f"Initializing Recommendation System from data in '{DATA_DIRECTORY}'... This might take a moment.")
recommender = None
try:
    # Initialize RecommendationSystem with SBERT and T5 model names
    recommender = RecommendationSystem(
        data_dir=DATA_DIRECTORY,
        embedding_model_name='sentence-transformers/all-MiniLM-L6-v2', # Using SBERT
        explanation_model_name='VietAI/vit5-base' # Using T5 for explanation
    )
    print("Recommendation System initialization attempt complete.")
except Exception as e:
    print(f"FATAL ERROR during Recommendation System initialization: {e}")
    recommender = None

# No external API readiness checks needed here now


# --- Flask Routes ---
@app.route('/login', methods=['GET', 'POST'])
def login():
    sample_user_ids = []
    if recommender and recommender.profiles_df is not None and not recommender.profiles_df.empty:
         sample_user_ids = recommender.profiles_df['user_id'].tolist()[:10]

    if request.method == 'POST':
        user_id = request.form.get('user_id', '').strip()
        if user_id:
            if recommender and recommender.profiles_df is not None and not recommender.profiles_df.empty:
                 if user_id not in recommender.profiles_df['user_id'].tolist():
                      return render_template('login.html', error=f"Mã sinh viên '{user_id}' không tồn tại trong dữ liệu hồ sơ sinh viên.", sample_user_ids=sample_user_ids, user_id=user_id)
            elif recommender is None:
                 print(f"Warning: Recommender system failed to initialize, cannot check user ID '{user_id}' against profiles.")

            session['user_id'] = user_id
            print(f"User '{user_id}' logged in.")
            return redirect(url_for('index'))
        else:
            return render_template('login.html', error="Vui lòng nhập Mã Sinh viên.", sample_user_ids=sample_user_ids)

    return render_template('login.html', sample_user_ids=sample_user_ids)

@app.route('/logout')
def logout():
    session.pop('user_id', None)
    print("User logged out.")
    return redirect(url_for('login'))


@app.route('/', methods=['GET'])
def index():
    user_id = session.get('user_id')
    if not user_id:
        return redirect(url_for('login'))
    return render_template('index.html', current_user_id=user_id)


@app.route('/recommend', methods=['POST'])
def recommend():
    """
    Handle recommendation request. Calls the document recommendation system.
    Returns JSON with 'recommendations' (list of docs with explanation) or 'error'.
    """
    user_id = session.get('user_id')
    if not user_id:
        return jsonify({"error": "Bạn chưa đăng nhập."}), 401

    request_data = request.get_json()
    query = request_data.get('query', '').strip()

    if not query:
        return jsonify({"error": "Vui lòng nhập nội dung truy vấn."})

    # --- Save query to history ---
    history_manager.add_query_to_history(user_id, query)
    # --- End save history ---

    start_time = time.time()
    # Initialize response_data with logged query info
    response_data = {"logged_query": {"user_id": user_id, "query": query, "timestamp": datetime.datetime.now().isoformat()}}

    try:
        # --- Call the document recommendation system ---
        # Check recommender readiness before calling
        if recommender is None or not recommender.is_ready:
             response_data["error"] = "Hệ thống gợi ý tài liệu chưa sẵn sàng. Vui lòng kiểm tra quá trình khởi tạo (mô hình Embedding, FAISS, mô hình Giải thích, dữ liệu)."
             response_data["recommendations"] = []
        else:
            # Call the recommendation logic
            # This call returns a list of dictionaries (docs with explanation) or []
            # and an error string (or None)
            recommendations, doc_rec_error = recommender.get_recommendations(user_id, query, top_n=5, k_retrieval=20)

            if doc_rec_error:
                response_data["error"] = doc_rec_error
                response_data["recommendations"] = []
            elif recommendations:
                # Recommendations list already contains 'doc_id', 'title', 'explanation', 'source'
                response_data["recommendations"] = recommendations
                # Source in this context indicates the source of the candidate (e.g., CBF_Query, CF)
                # The explanation is generated by T5/Template

            else:
                 # No recommendations found by the system (and no specific error message was returned)
                 response_data["error"] = f"Không tìm thấy gợi ý tài liệu phù hợp với truy vấn '{query}'. Vui lòng thử lại."
                 response_data["recommendations"] = []


    except Exception as e:
        # Catch any unexpected errors during the recommendation process
        response_data["error"] = f"Đã xảy ra lỗi không mong muốn trong quá trình xử lý yêu cầu: {e}"
        print(f"Unexpected error during request processing: {e}")

    end_time = time.time()
    print(f"Total request time for user {user_id}, query '{query}': {end_time - start_time:.2f} seconds.")

    # Determine the final response structure
    final_response_json = {}
    if "recommendations" in response_data and response_data["recommendations"]:
        final_response_json["recommendations"] = response_data["recommendations"]
        # You might add a general "source" or system name here if needed
        # final_response_json["system"] = "Document Recommendation System"

    elif "error" in response_data:
        final_response_json["error"] = response_data["error"]
        # final_response_json["system"] = "System Error"
    else:
         final_response_json["error"] = "Hệ thống không phản hồi."
         # final_response_json["system"] = "Unknown"

    # Add logged query info
    final_response_json["logged_query"] = response_data.get("logged_query")


    return jsonify(final_response_json)


@app.route('/api/history', methods=['GET'])
def api_get_history():
    user_id = session.get('user_id')
    if not user_id:
        return jsonify({"history": [], "error": "Bạn chưa đăng nhập."}), 401

    try:
        history = history_manager.get_query_history(user_id, limit=20)
        formatted_history = []
        for entry in history:
             timestamp_str = entry['timestamp'].isoformat() if isinstance(entry['timestamp'], datetime.datetime) else str(entry['timestamp'])
             formatted_history.append({
                 'user_id': entry['user_id'],
                 'query': entry['query'],
                 'timestamp': timestamp_str
             })

        return jsonify({"history": formatted_history, "error": None})
    except Exception as e:
        error_message = f"Đã xảy ra lỗi khi đọc lịch sử truy vấn: {e}"
        print(f"Error retrieving history via API for user {user_id}: {e}")
        return jsonify({"history": [], "error": error_message}), 500

# --- API ROUTE TO GET DOCUMENT LIST ---
@app.route('/api/documents', methods=['GET'])
def api_get_documents():
    """
    API endpoint to fetch the list of all documents (ID and Title).
    Requires login.
    Returns JSON: { "documents": [...], "error": "..." }
    """
    if not session.get('user_id'):
        return jsonify({"documents": [], "error": "Bạn chưa đăng nhập."}), 401

    # Check if recommender and document data are available
    if recommender is None or recommender.documents_df is None or recommender.documents_df.empty:
         return jsonify({"documents": [], "error": "Hệ thống gợi ý hoặc dữ liệu tài liệu chưa sẵn sàng."}), 500

    try:
        documents_list = recommender.documents_df[['doc_id', 'title']].to_dict('records')
        return jsonify({"documents": documents_list, "error": None})
    except Exception as e:
        error_message = f"Đã xảy ra lỗi khi lấy danh sách tài liệu: {e}"
        print(f"Error retrieving document list via API: {e}")
        return jsonify({"documents": [], "error": error_message}), 500

# --- Run the Flask App ---
if __name__ == '__main__':
    history_manager.init_db() # This also creates data dir

    data_dir_path = 'data'
    # Optional: Create dummy data if files don't exist for easier testing
    if not os.path.exists(os.path.join(data_dir_path, 'documents.csv')):
        print("Data files not found. Creating dummy data...")
        os.makedirs(data_dir_path, exist_ok=True)
        dummy_docs_data = {
            'item_id': [f'DOC{i:03d}' for i in range(100)],
            'title': [f'Bài giảng môn học {i+1}' for i in range(100)],
            'abstract': [f'Tóm tắt nội dung bài giảng {i+1} về chủ đề X, Y, Z.' for i in range(100)],
            'keywords': [f'môn học {i+1}, chủ đề X, chủ đề Y' for i in range(100)],
            'subject': [f'Môn {i % 15 + 1}' for i in range(100)],
            'relevant_majors': [f'Ngành {i % 5 + 1}, Ngành {(i+1) % 5 + 1}' for i in range(100)]
        }
        dummy_docs = pd.DataFrame(dummy_docs_data)

        dummy_profiles_data = {
            'user_id': [f'SGU{i:03d}' for i in range(50)],
            'major': [f'Ngành {i % 5 + 1}' for i in range(50)],
            'year': [i % 4 + 1 for i in range(50)]
        }
        dummy_profiles = pd.DataFrame(dummy_profiles_data)

        dummy_interactions_data = {
            'user_id': [f'SGU{i % 50:03d}' for i in range(200)],
            'content_id': [f'DOC{i % 100:03d}' for i in range(200)],
            'action_type': ['view', 'download'][i % 2],
            'timestamp': [datetime.datetime.now() - datetime.timedelta(days=i) for i in range(200)]
        }
        dummy_interactions = pd.DataFrame(dummy_interactions_data)

        dummy_docs.to_csv(os.path.join(data_dir_path, 'documents.csv'), index=False)
        dummy_profiles.to_csv(os.path.join(data_dir_path, 'student_profiles.csv'), index=False)
        dummy_interactions.to_csv(os.path.join(data_dir_path, 'interactions.csv'), index=False)
        print("Dummy data created.")
    else:
        print("Data files found.")


    app.run(debug=True, port=5000)